task_manager/statuses/urls.py
from django.urls import path
from task_manager.statuses import views

app_name = 'statuses'

urlpatterns = [
    path(
        '',
        views.StatusIndexView.as_view(),
        name='status_index'
    ),
    path(
        'create/',
        views.StatusFormCreateView.as_view(),
        name='status_create'
    ),
    path(
        '<int:pk>/update/',
        views.StatusFormUpdateView.as_view(),
        name='status_update'
    ),
    path(
        '<int:pk>/delete/',
        views.StatusDeleteView.as_view(),
        name='status_delete'
    ),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='base'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserIndexView.as_view(), name='index'),
    path('create/', views.UserFormCreateView.as_view(), name='user_create'),
    path('<int:pk>/update/', views.UserFormUpdateView.as_view(), name='user_update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
]

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    REQUIRED_FIELDS = [
        'first_name',
        'last_name',
    ]
    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.get_full_name()

task_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.utils.translation import gettext_lazy as _


class UserAuthenticationForm(AuthenticationForm):

    username = forms.CharField(
        label=_('Username'),
        widget=forms.TextInput(attrs={
            'class': 'w-50 form-control mb-3',
            'placeholder': _('Username'),
        })
    )

    password = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(attrs={
            'class': 'w-50 form-control mb-3',
            'placeholder': _('Password'),
        })
    )

task_manager/statuses/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Status


class StatusForm(forms.ModelForm):

    name = forms.CharField(
        label=_('Status name'),
        min_length=6,
        max_length=30,
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': _('Status name'),
        })
    )

    class Meta:
        model = Status
        fields = ['name']

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import User


class UserForm(UserCreationForm):

    first_name = forms.CharField(
        label=_('First name'),
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': _('First name'),
        })
    )

    last_name = forms.CharField(
        label=_('Last name'),
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': _('Last name'),
        })
    )

    username = forms.CharField(
        label=_('Username'),
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': _('Username'),
        })
    )

    password1 = forms.CharField(
        label=_('Password'),
        min_length=6,
        max_length=25,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': _('Password'),
        }),
    )

    password2 = forms.CharField(
        label=_('Password confirmation'),
        min_length=6,
        max_length=25,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': _('Password confirmation'),
        }),
    )

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        ]
        max_lenghts = {
            'first_name': 30,
            'username': 20,
        }
        labels = {
            'first_name': _('First name'),
            'last_name': _('Last name'),
            'username': _('Username')
        }
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': _('First name'),
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': _('Last name'),
            }),
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Username'),
            }),
        }


class ChangeUserForm(UserForm, UserChangeForm):

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        ]

task_manager/statuses/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from .models import Status
from .forms import StatusForm


class StatusIndexView(
        LoginRequiredMixin,
        ListView,
):

    model = Status
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'

    login_url = 'login'
    permission_denied_message = _('You should be logged in to view statuses!')
    redirect_field_name = reverse_lazy('status_index')


class StatusFormCreateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreateView,
):

    model = Status
    form_class = StatusForm
    template_name = 'statuses/create_status.html'

    login_url = 'login'
    permission_denied_message = _('You should be logged in to create a status!')
    redirect_field_name = reverse_lazy('statuses:status_index')

    success_url = reverse_lazy('statuses:status_index')
    success_message = "Status was created successfully"


class StatusFormUpdateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    UpdateView,
):

    model = Status
    form_class = StatusForm
    template_name = 'statuses/update_status.html'

    login_url = 'login'
    permission_denied_message = _('You should be logged in to change a status!')
    redirect_field_name = reverse_lazy('statuses:status_index')

    success_url = reverse_lazy('statuses:status_index')
    success_message = "Status was updated successfully"


class StatusDeleteView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    DeleteView,
):

    model = Status
    template_name = 'statuses/delete_status.html'

    login_url = 'login'
    permission_denied_message = _('You should be logged in to delete a status!')
    redirect_field_name = reverse_lazy('statuses:status_index')

    success_url = reverse_lazy('statuses:status_index')
    success_message = "Status was deleted successfully"

task_manager/users/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from .models import User
from .forms import UserForm, ChangeUserForm


class UserIndexView(
        ListView
):

    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'


class UserFormCreateView(
        SuccessMessageMixin,
        CreateView
):

    model = User
    form_class = UserForm
    template_name = 'users/create_user.html'

    success_url = reverse_lazy('login')
    success_message = "%(username)s was created successfully"


class UserFormUpdateView(
        UserPassesTestMixin,
        SuccessMessageMixin,
        UpdateView,
):

    model = User
    form_class = ChangeUserForm
    template_name = 'users/update_user.html'

    success_url = reverse_lazy('users:index')
    success_message = "%(username)s was updated successfully"

    def test_func(self):
        return self.get_object() == self.request.user

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                _('You need to be logged in for changing the user!')
            )
            return redirect('login')
        messages.error(
            self.request,
            _("You can't change another user!")
        )
        return redirect('users:index')


class UserDeleteView(
        UserPassesTestMixin,
        SuccessMessageMixin,
        DeleteView,
):

    model = User
    template_name = "users/delete_user.html"

    success_url = reverse_lazy('users:index')
    success_message = "User was deleted successfully"

    def test_func(self):
        return self.get_object() == self.request.user

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                _('You need to be logged in for deleting the user!')
            )
            return redirect('login')
        messages.error(
            self.request,
            _("You can't delete another user!")
        )
        return redirect('users:index')

task_manager/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import UserAuthenticationForm


def index(request):
    return render(request, 'base.html')


class UserLoginView(LoginView):
    template_name = 'login.html'
    authentication_form = UserAuthenticationForm

    def get_success_url(self):
        messages.success(self.request, _('You are successfully logged in'))
        return reverse_lazy('base')


class UserLogoutView(LogoutView):

    def get_success_url(self):
        messages.success(self.request, _('You are successfully logged out'))
        return reverse_lazy('base')

task_manager/templates/users/create_user.html
{% extends 'users/user_form.html' %}
{% load i18n %}
{% load bootstrap4 %}


{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block name %}

<h1>{% trans 'Sign-up' %}</h1>
{% if messages %}
<div class="alert alert-primary" role="alert">
    {{ messages }}
</div>
{% endif %}

{% endblock %}


{% block form %}

<form method="post" action="{% url 'users:user_create' %}">

{% endblock %}

{% block button %}

<button type="submit" class="btn btn-outline-dark">{% trans 'Register' %}</button>

{% endblock %}

task_manager/templates/users/delete_user.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}


{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


{% block content %}

<h1>{% trans 'Deleting a user' %}</h1>
<body>
    <form method="post" action="{% url 'users:user_delete' user.id %}">
        {% csrf_token %}
        <p class="h5 text-danger my-3">
            {% trans 'Are you sure you want to delete' %} {{ user.username }}?
        </p>
        <input class="btn btn-outline-danger my-3" type="submit" value="{% trans 'Yes, delete' %}">
    </form>
</body>
{% endblock %}

task_manager/templates/users/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}


{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


{% block content %}

<h1>{% trans 'Users' %}</h1>

<body>
    <table class="table table-light table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">{% trans 'Username' %}</th>
                <th scope="col">{% trans 'Fullname' %}</th>
                <th scope="col">{% trans 'Creation date' %}</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <th scope="row">{{ user.id }}</th>
                <td>{{ user.username}}</td>
                <td>{{ user.get_full_name }}</td>
                <td>{{ user.date_joined|date:"d.m.Y H:i" }}</td>
                <td>
                    <a class="btn btn-outline-dark btn-sm my-1" href="{% url 'users:user_update' user.id %}" role="button">{% trans 'Update' %}</a>
                    <a class="btn btn-outline-danger btn-sm my-1" href="{% url 'users:user_delete' user.id %}" role="button">{% trans 'Delete' %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

{% endblock %}

task_manager/templates/users/update_user.html
{% extends 'users/user_form.html' %}
{% load i18n %}
{% load bootstrap4 %}


{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block name %}

<h1>{% trans 'User update' %}</h1>

{% endblock %}


{% block form %}

<form method="post" action="{% url 'users:user_update' user.id %}">

{% endblock %}


{% block button %}

<button type="submit" class="btn btn-outline-dark">{% trans 'Update' %}</button>

{% endblock %}

task_manager/templates/users/user_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}


{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


{% block content %}

{% block name %}

{% endblock %}

<body>
    {% block form %}

    {% endblock %}
      {% csrf_token %}
      {% if form.errors %}
      <ul class="text-danger">
        {% for field in form %}
          {% for error in field.errors %}
          <li>
            {{ error|escape }}
          </li>
          {% endfor %}
        {% endfor %}
      </ul>
      {% endif %}
      <div class="row g-3">
        <div class="col">
            <label for="{{ form.first_name.id_for_label }}" class="form-label h5 mt-3">{{ form.first_name.label }}</label>
            {{ form.first_name }}
        </div>
        <div class="col">
            <label for="{{ form.last_name.id_for_label }}" class="form-label h5 mt-3">{{ form.last_name.label }}</label>
            {{ form.last_name }}
        </div>
      </div>
      <div class="mb-3">
        <label for="{{ form.username.id_for_label }}" class="form-label h5 mt-3">{{ form.username.label }}</label>
        {{ form.username }}
        <div id="{{ form.username.id_for_label }}" class="form-text mb-3">{% trans 'Maximum lenght of 20 symbols. You can only use letters, cyphers or symbols (@ + - _ .)' %}</div>
      </div>
      <div class="mb-3">
        <label for="{{ form.password1.id_for_label }}" class="form-label h5 mt-3">{{ form.password1.label }}</label>
        {{ form.password1 }}
        <div id="{{ form.password1.id_for_label }}" class="form-text mb-3">{% trans 'The lenght of your password should be between 6 and 25 characters' %}</div>
      </div>
      <div class="mb-3">
        <label for="{{ form.password2.id_for_label }}" class="form-label h5 mt-3">{{ form.password2.label }}</label>
        {{ form.password2 }}
        <div id="{{ form.password2.id_for_label }}" class="form-text mb-3">{% trans 'Please confirm your password by introducing it one more time' %}</div>
      </div>
        {% block button %}
        
        {% endblock %}
    </form>
</body>

{% endblock %}